{% set version = "0.12.1" %}

package:
  name: tensorflow-addons-base
  version: {{ version }}

source:
  git_url: https://github.com/tensorflow/addons.git
  git_rev: v{{ version }}
  patches:
    - 0001-Fix-build-on-ppc.patch  #[ppc64le] 

build:
  number: 1
  string: {{ build_type }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}   #[build_type == 'cpu']
  string: {{ build_type }}{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }} #[build_type == 'cuda']
{% if build_type == 'cuda' %}
  script_env:
    - CUDA_HOME
{% endif %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel >=3.7.2
    - git >={{ git }}
  host:
    - python  {{ python }}
    {% if build_type == 'cuda' %}
    - cudatoolkit {{ cudatoolkit }}
    - cudnn {{ cudnn }}
    - nccl {{ nccl }}
    {% endif %}
    - tensorflow-base {{ tensorflow }}
  run:
    - python  {{ python }}
    {% if build_type == 'cuda' %}
    - cudatoolkit {{ cudatoolkit }}
    - cudnn {{ cudnn }}
    - nccl {{ nccl }}
    {% endif %}
    - tensorflow-base {{ tensorflow }}
    - tensorflow-addons-select {{ tf_addons_select_version }}

about:
  home: https://www.tensorflow.org/addons/
  license: Apache-2.0
  license_family: Apache
  license_file: {{ SRC_DIR }}/LICENSE
  summary: "A library that implements new functionality not available in core TensorFlow."
  description: |
     TensorFlow Addons is a repository of contributions that conform to well-established API patterns,
     but implements new functionality not available in core.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
